downgrade activesupport to work around some bizarre gem interaction.
With this Gemfile:

  source 'http://rubygems.org'
  gem 'json', '= 1.4.6'
  gem 'hashie', '= 0.2.2'
  gem 'activesupport', '= 3.0.2'
  gem 'feedzirra', '= 0.0.24'
  gem 'i18n', '= 0.4.2'

Run this script:

  require 'bundler'
  Bundler.require
  require 'json'
  require 'hashie'
  JSON.pretty_generate(Hashie::Mash.new)

And see this error:

/home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/json/encoding.rb:61:in `options_for': undefined method `merge' for #<JSON::Ext::Generator::State:0xa154e38> (NoMethodError)
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/json/encoding.rb:46:in `block in encode'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/json/encoding.rb:77:in `check_for_circular_references'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/json/encoding.rb:45:in `encode'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/json/encoding.rb:30:in `encode'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.2/lib/active_support/core_ext/object/to_json.rb:20:in `to_json'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/hashie-0.2.2/lib/hashie/hash.rb:19:in `to_json'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/json-1.4.6/lib/json/common.rb:264:in `generate'
  from /home/bronson/.rvm/gems/ruby-1.9.2-p0/gems/json-1.4.6/lib/json/common.rb:264:in `pretty_generate'
  from console:5:in `<main>'